# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bayesianfin',
                'doc_host': 'https://sofeikov.github.io',
                'git_url': 'https://github.com/sofeikov/bayesianfin',
                'lib_path': 'bayesianfin'},
  'syms': {'bayesianfin.core': {'bayesianfin.core.foo': ('core.html#foo', 'bayesianfin/core.py')}}}
